### ISSUE TITLE
ofxGizmo in android

### ISSUE THREAD

**Issue by Angie-Ie** [NickHardeman/ofxGizmo#1]
i am trying to use ofxGizmo in android, it is possible? i am try but get error in LibGizmo/ZMathsFunc.h.. please help me, thank you

**Comment by NickHardeman** [comment]
Hmm. Haven't tested on Android. Can you provide more information about the error?

**Comment by Angie-Ie** [comment]
this is the error:
`/of_v0.9.3_android_release/addons/ofxGizmo/libs/LibGizmo/ZBaseMaths.inl: In member function 'void tmatrix::RotationY(float)':
  float c = (float)MathCos(angle);
                                ^
  float s = (float)MathSin(angle);
                                ^
/of_v0.9.3_android_release/addons/ofxGizmo/libs/LibGizmo/ZBaseMaths.inl: In member function 'void tmatrix::RotationZ(float)':
  float c = (float)MathCos(angle);
                                ^
  float s = (float)MathSin(angle);
                                ^
/of_v0.9.3_android_release/addons/ofxGizmo/libs/LibGizmo/ZBaseMaths.inl: In member function 'void tmatrix::RotationAxis(const tvector3&, float)':
  float s = (float)MathSin(angle);
                                ^
  float c = (float)MathCos(angle);
                                ^
/of_v0.9.3_android_release/addons/ofxGizmo/libs/LibGizmo/ZBaseMaths.inl: In member function 'void tmatrix::RotationYawPitchRoll(float, float, float)':
  float cy = (float)MathCos(yaw);
                               ^
  float sy = (float)MathSin(yaw);
                               ^
/of_v0.9.3_android_release/addons/ofxGizmo/libs/LibGizmo/ZBaseMaths.inl: In member function 'void tmatrix::PerspectiveFovRH(float, float, float, float)':
  float h = (float)MathCos(fovy/2) / (float)MathSin(fovy/2);
                                 ^
  float h = (float)MathCos(fovy/2) / (float)MathSin(fovy/2);`

**Comment by Angie-Ie** [comment]
hi, i can run ofxGizmo in android. 
 i am add #define __forceinline inline in ZMathsFunc.h  fix the error :)

**Comment by NickHardeman** [comment]
Hi @Angie-Ie , 
Can you send a pull request with the fix and I can merge it?
Or just paste the fix in the comments, if that's easier.

Best,
Nick

**Comment by Angie-Ie** [comment]
Hi @NickHardeman , in LibGizmo/ZMathsFunc.h add
`
#ifndef ZMATHSFUNCS_H
#define ZMATHSFUNCS_H
#define __forceinline inline  //add this



// Includes ///////////////////////////////////////////////////////////////////////////////////////

#include <math.h>
#include <stdlib.h>
#include "ZBaseDefs.h"`

// the rest is the same

**Comment by Angie-Ie** [comment]
Hi @NickHardeman , in LibGizmo/ZMathsFunc.h add
`
#ifndef ZMATHSFUNCS_H
#define ZMATHSFUNCS_H
#define __forceinline inline //add this

// Includes ///////////////////////////////////////////////////////////////////////////////////////

#include <math.h>
#include <stdlib.h>
#include "ZBaseDefs.h"`

// the rest is the same
