### ISSUE TITLE
Not able to compile on Win64

### ISSUE THREAD

**Issue by Akiva42** [NickHardeman/ofxGizmo#2]
I'm attempting to incorporate ofxGizmo into my project. I'm using Windows 10 64bit, Visual Studio 2015 and OF 0.9.8. I have no trouble getting the example project running when I build for 32bit but when I switch to building for 64bit I get about 500 errors when compiling. It seems that most of these errors relate to this: " '__asm' keyword not supported on this architecture ".

Is it possible to use ofxGizmo with 64bit Windows?

Thanks

**Comment by moebiussurfing** [comment]
hey @Akiva42 , did you get it working on 64bits?

**Comment by NickHardeman** [comment]
Sorry for the delay on this!! I just got a windows machine not too long ago. I was able to get it working on Windows 10 64 bit. The latest should be up.
