### ISSUE TITLE
erros compiling in Xcode 8.2.1 / 10.12.3 Sierra / OF 0.9.8/0.9.3

### ISSUE THREAD

**Issue by moebiussurfing** [NickHardeman/ofxGizmo#3]
hey @NickHardeman ,
any idea of how to solve this errors? I tried to rebuild the example project with the project generator and also with 32 or 64 bits without success. The libs seems to be detected on the project...
![ofxgizmo01](https://cloud.githubusercontent.com/assets/2106149/23053812/ab8994bc-f4ba-11e6-8714-880c7c7fa58a.jpeg)
![ofxgizmo02](https://cloud.githubusercontent.com/assets/2106149/23053813/ab8b65d0-f4ba-11e6-876d-364b484d3559.jpeg)
cheers

**Comment by NickHardeman** [comment]
Hi @moebiussurfing, sorry for the delay. I just tried the project generator to create a new addon example xcode project. It compiled for me, but I am on XCode 6.2 / 10.9.5 / OF 0.9.8. I removed the old xcode project because creating a fresh one every time seems to be the least error prone.
