### ISSUE TITLE
any chance to update to 0.10?

### ISSUE THREAD

**Issue by moebiussurfing** [NickHardeman/ofxGizmo#5]
hey @NickHardeman ,
I tried to update to 0.10 modifying the OF core like on the https://github.com/pixelsandcandy/ofxFBX repo:

```
// ofNode.h
#include "ofMatrix4x4.h"
void setTransformMatrix(const ofMatrix4x4 &m44);

// ofNode.cpp
void ofNode::setTransformMatrix(const ofMatrix4x4 &m44) {
    ofVec3f position;
    ofQuaternion orientation;
    ofVec3f scale;
    ofQuaternion so;
    
    m44.decompose( position, orientation, scale, so );

    this->position = {position.x, position.y, position.z};
    this->orientation = orientation;
    this->scale = scale;
    
    onScaleChanged();
    onPositionChanged();
    onOrientationChanged();
    
    createMatrix();
} 
```
I copied some functions from OF98 to ofNode and ofCamera...
I ckecked also your new commits on ofxFBX but I am stucked...
Any change to get this working? maybe is too much work... i don't know

Now I am testing in OF masterbranch, MacOS High Sierra / xCode 9 , 10

**Comment by NickHardeman** [comment]
Hmm. I am going to take a look. OF 0.10 removed that beloved ofNode function where you could set the matrix directly. Since upgrading ofFBX to OF 0.10 I learned a lot. I need this for a project, so going to take a stab at it! 👍

**Comment by NickHardeman** [comment]
Just pushed up a version that works with OF 0.10 the stable version. I added an apply( ofNode& anode ) function to the gizmo. So you can pass your node in and have the gizmo transform it. :)

**Comment by moebiussurfing** [comment]
thanks!!! it's working here in master branch :)
