### ISSUE TITLE
How to know when ofxGizmo wants to capture the mouse

### ISSUE THREAD

**Issue by koreus7** [NickHardeman/ofxGizmo#8]
At the moment the camera is moving with the gizmo. If I turn off the camera then it works but I don't want to a toggle switch. No 3D application has this, they all know when you have clicked the gizmo.

Is there a way to detect if the mouse down happened inside the gizmo and so conditionally disable the mouse movement for ofEasyCam?

ImGUI for example has `io.wantCaptureMouse` https://github.com/ocornut/imgui so I know when to ignore mouse events.

**Comment by koreus7** [comment]
I discovered isInteracting() which seems to be what I need.

**Comment by koreus7** [comment]
The above fix solves the problem for active interactions but not hover states. Does LibGizmo expose this?

**Comment by NickHardeman** [comment]
Thank you, merged.
